name: Release

on:
  push:
    tags:
      - 'v*.*.*'

  release:
    types: 
      - published  # Triggers when a release is published
      - edited     # Trigger when a release is edtied

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      # Restore the dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build the solution
        run: dotnet build Chirp.sln --configuration Release --no-restore

      # Run tests
      - name: Run tests
        run: dotnet test --configuration Release --verbosity normal

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: makedir
        run: mkdir -p ./publish  
      
      - name: make releases
        run: dotnet publish "src/Chirp.Razor/Chirp.Razor.csproj" -c Release -r osx-x64 --self-contained false /p:PublishSingleFile=true --output ./publish/macos
      
      - name: Zip the published files
        run: zip -r ./publish/macOS/macos-x64.zip ./publish/macOS/*

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: myapp
          path: ./publish/macOS/myapp.zip

      - name: Install tree
        run: sudo apt-get install tree
    
      - name: Show directory structure
        run: tree -a
