name: Release

on:
  push:
    tags:
      - 'v*.*.*'

  release:
    types: 
      - published  # Triggers when a release is published
      - edited     # Trigger when a release is edtied

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      # Restore the dependencies
      - name: Restore dependencies
        run: dotnet restore

      # Build the solution
      - name: Build the solution
        run: dotnet build Chirp.sln --configuration Release --no-restore

      # Run tests
      - name: Run tests
        run: dotnet test --configuration Release --verbosity normal

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: makedir
        run: mkdir -p ./publish  
      
      - name: make releases
        run: dotnet publish "src/Chirp.Razor/Chirp.Razor.csproj" -c Release -r osx-x64 --output ./publish/macos
      
      - name: Zip the published files
        run: zip -r ./publish/macos-x64.zip ./publish/macos/*

      - name: Upload Release Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-x64
          path: ./publish/macos-x64.zip

      - name: Show directory structure
        run: |
          sudo apt-get install tree
          tree -a ./publish
      
  upload:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Download Release Artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-x64

      - name: Release with tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./macos-x64.zip
