  name: Release

  on:
    push:
      tags:
        - 'v*.*.*'

    release:
      types: 
        - published  # Triggers when a release is published
        - edited     # Trigger when a release is edtied

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Setup .NET
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.x

        # Restore the dependencies
        - name: Restore dependencies
          run: dotnet restore

        # Build the solution
        - name: Build the solution
          run: dotnet build Chirp.sln --configuration Release --no-restore

        # Run tests
        - name: Run tests
          run: dotnet test --configuration Release --verbosity normal

    release:
      needs: build
      runs-on: ubuntu-latest
      strategy:
        matrix:
          os: [osx-x64, linux-x64, win-x64]

      steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: makedir
          run: mkdir -p ./publish  
        
        - name: make releases
          run: dotnet publish -c Release -r ${{ matrix.os }} --self-contained /p:PublishSingleFile=true --output ./publish/${{ matrix.os }}
        
        - name: Zip the published files
          run: zip -r ./publish/${{ matrix.os }} ./publish/${{ matrix.os }}

        - name: Upload Release Artifact
          uses: actions/upload-artifact@v3
          with:
            name: ${{ matrix.os }}
            path: ./publish/${{ matrix.os }}.zip

        - name: Show directory structure
          run: |
            sudo apt-get install tree
            tree -a ./publish

        - name: Download Release Artifact
          uses: actions/download-artifact@v3
          with:
            name: ${{ matrix.os }}

        - name: Release with tag
          uses: softprops/action-gh-release@v1
          with:
            files: |
              ./${{ matrix.os }}.zip

      
