name: Bump Version and Create Release

on:
  push:
    branches:
      - main
      - release-yaml

jobs:
  
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history and tags


      # Get the version from Git tags to use for tagging the release
      - name: Get version from Git tags
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "version=$VERSION" >> $GITHUB_ENV

      # Step 5: Create a new GitHub Release with the updated version
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "${{ env.version }}"
          release_name: "Release ${{ env.version }}"
          draft: false
          prerelease: false
